# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())




2.1.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0n6rph84/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0n6rph84/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0n6rph84/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0n6rph84/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

#### 3. Create a null vector of size 10

In [4]:
arr=np.zeros(10)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [5]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add

<ufunc 'add'>

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
are=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.  Create a vector with values ranging from 10 to 49

In [9]:
arr=np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 8.  Reverse a vector (first element becomes last)

In [12]:
m=np.flipud(arr)
print(m)

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


9.  Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
arr = np.random.randint(0,9,(3,3))
arr

array([[3, 0, 7],
       [4, 3, 8],
       [5, 3, 7]], dtype=int32)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [28]:
arr = np.array([1,2,0,0,4,0])
ans =  np.nonzero(arr)
ans

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [26]:
np.random.random((3,3,3))

array([[[0.69024586, 0.10107588, 0.85259174],
        [0.50222477, 0.16713315, 0.88881827],
        [0.70976174, 0.9046028 , 0.95253034]],

       [[0.88364467, 0.90960877, 0.50348685],
        [0.81142009, 0.50940955, 0.92422837],
        [0.59124314, 0.13023198, 0.41258234]],

       [[0.53580204, 0.54901848, 0.97385813],
        [0.82769607, 0.78016733, 0.70890012],
        [0.16842381, 0.82750865, 0.10858132]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr = np.random.random((10,10))
a = np.max(arr)
b = np.min(arr)
print(a,b,sep="\n")

0.9992863684822637
0.02269093175742143


#### 14. Create a random vector of size 30 and find the mean value

In [24]:
arr = np.random.random((30))
ans = np.mean(arr)
ans

np.float64(0.5086947839424943)

#### 15. Create a 2d array with 1 on the border and 0 inside

In [23]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [22]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
arr=np.diag([1,2,3,4],-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [13]:
arr.unravel_index(99,(6,7,8))

AttributeError: 'numpy.ndarray' object has no attribute 'unravel_index'

In [17]:
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))